### PR TITLE
Fixes for the current teamspeak version

### PR DESCRIPTION
**Pull request by Flakebi**
Hi, this are the changes I needed to make so it works with the current TeamSpeak version.
The download address changed slightly (and I saw the other open pull request too late so the template issue is fixed in another way).

### CODE REVIEW

**Comment by StrangeWill** [comment]
Thanks, can't believe I missed the last PR I said I'd pull in, going to review everything right now...

**Comment by StrangeWill** [comment]
Odd -- I see you updated the links to .tar.bz2 files, but I don't see those here: http://dl.4players.de/ts/releases/3.0.11.3/

I'm also making various other tweaks as needed.

**Comment by StrangeWill** [comment]
Nix that, I was locking to 3.0.11.3 like a dork, they changed it between then and now.

**Comment by Flakebi** [comment]
Thanks for the fast fixes!

**Pull request merged**
